[package]
name = "todo"
version = "0.1.0"
authors = ["Bill Yu <billyuhan@gmail.com>"]

[dependencies]
clap = {version = "~2.31.2", features = ["yaml"]}
reqwest = "0.8.6"
serde = "1.0"
serde_derive = "1.0"